name: Maintanence
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #esys_flutter_share: ^1.0.2
  path_provider: ^0.4.1
  http: ^0.12.0+4
  flutter:
    sdk: flutter
  cupertino_icons: any
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0
  qr_flutter: ^3.1.0
  qrscan: ^0.2.17

dev_dependencies:
  http: ^0.12.0+4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

